<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.OpenGL" Version="2.23.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <!-- Copy ressources to the output directory-->
  <ItemGroup>
    <None Include="ressources\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <Link>ressources\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="ressources\Shaders\arrow.vert.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="ressources\Shaders\arrow.vert.cs" />
  </ItemGroup>


</Project>
